---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.db.name }}
spec:
  type: {{ .Values.service.db.type }}
  selector:
    app: {{ .Values.deployment.db.name }}
  ports:
    - port: {{ .Values.service.db.port }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.app.name }}
  labels:
    app: {{ .Values.deployment.app.name }}
spec:
  type: {{ .Values.service.app.type }}
  selector:
    app: {{ .Values.deployment.app.name }}
  ports:
    - protocol: {{ .Values.service.app.protocol }}
      name: {{ .Values.service.app.name }}
      port: {{ .Values.service.app.port }}
      targetPort: {{ .Values.service.app.port }}


---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.monitor.app.name }}
  labels:
    app: {{ .Values.monitor.app.name }}
spec:
  endpoints:
    - port: {{ .Values.service.app.name }}
      scrapeTimeout: 30s
      path: /actuator/prometheus
      honorLabels: true
      scheme: http
  namespaceSelector:
    matchNames:
      - auth
  selector:
    matchLabels:
      app: {{ .Values.deployment.app.name }}