{
 "title": "New dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "/register",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 19, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_bucket{uri=\"/register\", le=\"+Inf\"} [2m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "/login",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 19, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_bucket{uri=\"/login\", le=\"+Inf\"} [2m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "catalog search",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_bucket{uri=\"/api/v1/products/{id}\", le=\"+Inf\"} [2m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "catalog get product",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_bucket{uri=\"/api/v1/products/{id}\", le=\"+Inf\"} [2m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cart add / cart get",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_bucket{uri=\"/api/v1/cart/products/\", le=\"+Inf\"} [2m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "создание заказа",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 20, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_bucket{uri=\"/order/create\", le=\"+Inf\"} [2m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "order выбрать место доставки",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_bucket{uri=\"/order/chooseADeliveryLocation\", le=\"+Inf\"} [2m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "order выбрать способ оплаты",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 20, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_bucket{uri=\"/order/chooseAPaymentMethod\", le=\"+Inf\"} [2m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "order Выбрать время доставки",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_bucket{uri=\"/order/chooseTheDeliveryTime\", le=\"+Inf\"} [2m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "order Зарезервировать курьера",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_bucket{uri=\"/order/courierReserve\", le=\"+Inf\"} [2m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "order get",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 19, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_bucket{uri=\"/order/get\", le=\"+Inf\"} [2m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "order pay",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 19, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_bucket{uri=\"/order/pay\", le=\"+Inf\"} [2m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}